### ISSUE TITLE
AutocompleteInput does not render correctly first time

### ISSUE THREAD

**Issue by BenjaminFaal** [MhdSyrwan/aor-embedded-array#13]
Please see https://github.com/marmelab/admin-on-rest/pull/1177

**Comment by MhdSyrwan** [comment]
Please provide the failing test case using a service like https://codesandbox.io so i can debug it.

**Comment by MhdSyrwan** [comment]
closed due to inactivity. feel free to reopen it again when you have time to discuss the issue.
