### ISSUE TITLE
Can we please have an usage example

### ISSUE THREAD

**Issue by style2joy** [MhdSyrwan/aor-embedded-array#14]
I have tried my best to use it in my project. A full example or a sandbox like [this](https://codesandbox.io/s/ElxGNxBY0) will be very helpful. Thanks

**Comment by MhdSyrwan** [comment]
Good idea. a full example in a sandbox would be great to make sure people can use it 100% right.
I will work on this today or tomorrow.

**Comment by style2joy** [comment]
Thank you so much, I have not been able to figure out how to use this correctly yet. Also I have slightly different requirement ([asked here](https://stackoverflow.com/questions/47691114/master-detail-parent-child-input-form-with-admin-on-rest)). Do you think `aor-embedded-array` can help me with that. (Sorry, I am still novice in React/AOR)

**Comment by MhdSyrwan** [comment]
check this sandbox [link](https://codesandbox.io/s/zlro1q2364), there you'll find a form tab named "Metadata" in `posts.js`.

**Comment by style2joy** [comment]
👍  Great! this helps..
Thanks :)
