### ISSUE TITLE
Add button icon should be '+'

### ISSUE THREAD

**Issue by ashimsaha2311** [MhdSyrwan/aor-embedded-array#27]
The icon of add button should be '+', now it looks similar to edit icon, so a little bit confusing.

![image](https://user-images.githubusercontent.com/32305652/36458198-9d742de2-16d3-11e8-8ff9-e3192c99ffb3.png)

**Comment by MhdSyrwan** [comment]
Pull request merged.

**Comment by MhdSyrwan** [comment]
published, check version `0.0.8`
