### ISSUE TITLE
Increase visibility of this repo

### ISSUE THREAD

**Issue by christiaanwesterbeek** [MhdSyrwan/aor-embedded-array#31]
Since [it is preferred](https://github.com/marmelab/admin-on-rest/pull/697#issuecomment-327118724) that some features live as an external package, it helps to be able to find them more easily. For that purpose, could you [add the topics](https://help.github.com/articles/about-topics/) `admin-on-rest`, `react-admin` to this repo?

And could you add an examples paragraph to README.md that shows screenshots of how the UI of EmbeddedArrayField of EmbeddedArrayInput look like?

**Comment by MhdSyrwan** [comment]
Topics have been added.
Regarding the screenshots, it could take some time unfortunately, will work on that next weekend.

**Comment by MhdSyrwan** [comment]
Done.
