### ISSUE TITLE
Support for react-admin 2.0.0 (ra-embedded-array?)

### ISSUE THREAD

**Issue by ilhad4ev** [MhdSyrwan/aor-embedded-array#33]
This is probably more like a query than an issue as I know this might be on the works already.

Do you have target release date for aor-embedded-array which is compatible with react-admin?
I have tried adding this in a react-admin@2.0.0-beta4 and it seems this is not yet usable.

Btw, thanks a lot for this tool. I badly need this. :D

**Comment by MhdSyrwan** [comment]
There was a PR (#24) to support react-admin 2.0.0. I will ask for status.

**Comment by MhdSyrwan** [comment]
Hi @ilhad4ev I have some good news for you.
They've just announced that this feature has been implemented in the core of `react-admin 2.0.0`.
Check https://github.com/marmelab/admin-on-rest/pull/697#issuecomment-379074510
And https://github.com/marmelab/admin-on-rest/pull/1717

**Comment by ilhad4ev** [comment]
Hi @MhdSyrwan! This is good news indeed. I'll try it immediately.
Thanks for your support! :)

**Comment by nitoygo** [comment]
ReferenceInput not working with ArrayInput.
How to do something like the following?
```
        <ArrayInput source="post">
          <SimpleFormIterator>
            <ReferenceInput source="commentedOn" reference="user">
              <AutocompleteInput optionText="username" />
            </ReferenceInput>
          </SimpleFormIterator>
        </ArrayInput>
```
