### ISSUE TITLE
Support for ReferenceField

### ISSUE THREAD

**Issue by sportluffi** [MhdSyrwan/aor-embedded-array#34]
There seems to be a problem when trying to use a <ReferenceField> in combination with EmbeddedArrayInput. 
I just can't get it to work - the reference field is not calling the endpoint, and therefore not displaying any data. 
Are there any known tricks for this?

**Comment by MhdSyrwan** [comment]
Can you please provide a complete example using https://codesandbox.io/

**Comment by MhdSyrwan** [comment]
closed due inactivity. please feel free to re-open this when you prepare the example.

**Comment by nitoygo** [comment]
ReferenceInput not working with ArrayInput.
How to do something like the following?
```
        <ArrayInput source="post">
          <SimpleFormIterator>
            <ReferenceInput source="commentedOn" reference="user">
              <AutocompleteInput optionText="username" />
            </ReferenceInput>
          </SimpleFormIterator>
        </ArrayInput>
```

**Comment by MhdSyrwan** [comment]
@nitoygo Actually it should work, please provide an example using https://codesandbox.io/

BTW, check this issue, it might help https://github.com/MhdSyrwan/aor-embedded-array/issues/5
Also, please provide a sample of the data you're using.
