### ISSUE TITLE
Add actions prop

### ISSUE THREAD

**Issue by bfintal** [MhdSyrwan/aor-embedded-array#7]
Add actions prop similar to how AOR allows for custom actions ala-`CardActions`. This would be great for extending the functionality aside from the remove button.

**Comment by MhdSyrwan** [comment]
In AOR those actions are backend powered via RESTful API or something like this. I'm wondering in a situation like this how it would be implemented ? is it just client-side powered ?

Can you provide a clear use case ?

**Comment by MhdSyrwan** [comment]
closed for inactivity.
